import type { Destination, LatLng } from "../types";

export const RCCG_CAMP_CENTER: LatLng = { lat: 6.8698, lng: 3.7292 };

export const RCCG_CAMP_BOUNDS = {
  north: 6.885,
  south: 6.855,
  east: 3.738,
  west: 3.72,
};

export const RCCG_CAMP_LOCATIONS: Destination[] = [
  {
    id: "main-auditorium",
    name: "Main Auditorium",
    aliases: ["new auditorium", "3km auditorium", "big church", "arena"],
    coordinates: { lat: 6.867, lng: 3.725 },
    category: "auditorium",
  },
  {
    id: "main-gate",
    name: "Main Entrance",
    aliases: ["main gate", "entrance", "express gate", "camp gate", "toll gate"],
    coordinates: { lat: 6.878, lng: 3.732 },
    category: "gate",
  },
  {
    id: "youth-centre",
    name: "Youth Centre",
    aliases: ["youth church", "youth arena", "rcyca", "youth"],
    coordinates: { lat: 6.8655, lng: 3.7285 },
    category: "facility",
  },
  {
    id: "bookshop",
    name: "Bookshop",
    aliases: ["book store", "bible store", "crm bookshop", "stationery"],
    coordinates: { lat: 6.8685, lng: 3.73 },
    category: "facility",
  },
  {
    id: "medical-centre",
    name: "RCCG Health Center",
    aliases: ["medical centre", "medical center", "hospital", "clinic", "health centre", "emergency"],
    coordinates: { lat: 6.872, lng: 3.728 },
    category: "facility",
  },
  {
    id: "bus-terminal",
    name: "Shuttle Park",
    aliases: ["bus terminal", "bus stop", "park", "garage", "transport park", "shuttle"],
    coordinates: { lat: 6.876, lng: 3.731 },
    category: "transit",
  },
  {
    id: "prayer-ground",
    name: "Prayer Garden",
    aliases: ["prayer ground", "prayer foyer", "prayer mountain", "altar", "pray"],
    coordinates: { lat: 6.863, lng: 3.7315 },
    category: "facility",
  },
  {
    id: "camp-hostels",
    name: "Camp Hostels",
    aliases: ["hostel", "visitor lodge", "chalets", "accommodation"],
    coordinates: { lat: 6.864, lng: 3.726 },
    category: "hostel",
  },
  {
    id: "eateries",
    name: "Eateries",
    aliases: ["food", "canteen", "restaurant", "food court", "buka", "kitchen"],
    coordinates: { lat: 6.869, lng: 3.7295 },
    category: "food",
  },
  {
    id: "admin-office",
    name: "National Secretariat",
    aliases: ["administrative office", "admin block", "secretariat", "governing office", "office"],
    coordinates: { lat: 6.8705, lng: 3.729 },
    category: "office",
  },
  {
    id: "prayer-foyer",
    name: "Prayer Foyer",
    aliases: ["foyer", "prayer hall", "prayer area"],
    coordinates: { lat: 6.8642, lng: 3.731 },
    category: "facility",
  },
  {
    id: "protocol-car-park",
    name: "Protocol Car Park",
    aliases: ["protocol parking", "vip park", "vip car park", "protocol"],
    coordinates: { lat: 6.8745, lng: 3.7305 },
    category: "facility",
  },
  {
    id: "car-park-c",
    name: "Car Park C",
    aliases: ["park c", "car park", "parking c"],
    coordinates: { lat: 6.8752, lng: 3.7296 },
    category: "facility",
  },
  {
    id: "redemption-way",
    name: "Redemption Way",
    aliases: ["redemption road", "main internal road"],
    coordinates: { lat: 6.8702, lng: 3.7305 },
    category: "transit",
  },
  {
    id: "akindayomi-way",
    name: "Akindayomi Way",
    aliases: ["rev akindayomi way", "akindayomi road"],
    coordinates: { lat: 6.8692, lng: 3.7274 },
    category: "transit",
  },
  {
    id: "holiness-road",
    name: "Holiness Road",
    aliases: ["holiness", "holiness rd"],
    coordinates: { lat: 6.8712, lng: 3.7276 },
    category: "transit",
  },
  {
    id: "canaanland-market",
    name: "Canaanland Market",
    aliases: ["market", "cannanland market", "shops", "camp market"],
    coordinates: { lat: 6.868, lng: 3.7287 },
    category: "food",
  },
  {
    id: "crm-shops",
    name: "CRM Shops",
    aliases: ["crm shop", "shopping area", "shops"],
    coordinates: { lat: 6.8684, lng: 3.7291 },
    category: "food",
  },
  {
    id: "open-heaven-parish",
    name: "RCCG Open Heaven Parish",
    aliases: ["open heaven", "open heavens parish", "parish"],
    coordinates: { lat: 6.871, lng: 3.7284 },
    category: "facility",
  },
  {
    id: "province-office",
    name: "RCCG Province Coordinating Office",
    aliases: ["province office", "coordinating office", "rccg province office"],
    coordinates: { lat: 6.8709, lng: 3.7294 },
    category: "office",
  },
  {
    id: "redeemer-school",
    name: "The Redeemer Nursery and Primary School",
    aliases: ["redeemer school", "nursery school", "primary school"],
    coordinates: { lat: 6.8716, lng: 3.7301 },
    category: "facility",
  },
  {
    id: "holy-ghost-congress-office",
    name: "Holy Ghost Congress Office",
    aliases: ["congress office", "holy ghost office", "hgc office"],
    coordinates: { lat: 6.8697, lng: 3.728 },
    category: "office",
  },
  {
    id: "white-house-suite",
    name: "White House Suite",
    aliases: ["white house", "suite", "guest suite"],
    coordinates: { lat: 6.8715, lng: 3.7288 },
    category: "hostel",
  },
  {
    id: "gethsemane-lodge",
    name: "Gethsemane Lodge",
    aliases: ["gethesmane lodge", "lodge", "guest lodge"],
    coordinates: { lat: 6.8662, lng: 3.7268 },
    category: "hostel",
  },
  {
    id: "dormitories",
    name: "Dormitories",
    aliases: ["yellow dormitories", "dormitory", "dorms", "accommodation"],
    coordinates: { lat: 6.8648, lng: 3.7258 },
    category: "hostel",
  },
  {
    id: "meditation-centre",
    name: "Meditation Centre",
    aliases: ["meditation center", "quiet place", "retreat centre"],
    coordinates: { lat: 6.8668, lng: 3.7275 },
    category: "facility",
  },
  {
    id: "crm-press",
    name: "CRM Press",
    aliases: ["press", "printing press", "rccg press"],
    coordinates: { lat: 6.8675, lng: 3.7279 },
    category: "office",
  },
  {
    id: "water-works",
    name: "Water Works",
    aliases: ["waterworks", "water station", "water plant"],
    coordinates: { lat: 6.866, lng: 3.7298 },
    category: "facility",
  },
];

export const POPULAR_DESTINATION_IDS = [
  "main-auditorium",
  "prayer-ground",
  "eateries",
  "bus-terminal",
  "bookshop",
  "admin-office",
  "medical-centre",
];
